apiVersion: v1
kind: Service
metadata:
  name: skylite-weather-api
  labels:
    app.kubernetes.io/name: skylite-weather
    app.kubernetes.io/component: api
spec:
  selector:
    app.kubernetes.io/name: skylite-weather
    app.kubernetes.io/component: api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP